apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestor-rabbit
  template:
    metadata:
      labels:
        app: ingestor-rabbit
        tier: broker
spec:
  replicas: 1
  containers:
  - name: ingestor-rabbit
    image: rabbitmq:3
    ports:
    - containerPort: 5672
      protocol: TCP
    - containerPort: 4369
      protocol: TCP
    - containerPort: 25672
      protocol: TCP
    - containerPort: 25671
      protocol: TCP