apiVersion: v1
kind: Service
metadata:
  name: ingestor-rabbit
spec:
  ports:
  - name: primary
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: handshake
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: worker1
    port: 25672
    protocol: TCP
    targetPort: 25672
  - name: worker2
    port: 25671
    protocol: TCP
    targetPort: 25671
  selector:
    app: ingestor-rabbit