apiVersion: v1
kind: Service
metadata:
  name: ingestor-rabbit
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  - port: 4369
    protocol: TCP
    targetPort: 4369
  - port: 25672
    protocol: TCP
    targetPort: 25672
  - port: 25671
    protocol: TCP
    targetPort: 25671
  selector:
    app: ingestor-rabbit