apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestor-rabbit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ingestor-rabbit
        tier: broker
    spec:
      containers:
      - name: ingestor-rabbit
        image: rabbitmq:3
        ports:
        - containerPort: 5672
          protocol: TCP
        - containerPort: 4369
          protocol: TCP
        - containerPort: 25672
          protocol: TCP
        - containerPort: 25671
          protocol: TCP